[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Blog"
  url = "blog/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Resources"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "Glossary"
  url = "resources/glossary/"
[[main]]
  parent = "Links"
  name = "Boycott List"
  url = "resources/boycott_list/"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/ClallamLGBT"
# [[social]]
#   name = "twitter"
#   weight = 2
#   url = "https://twitter.com/#"
# [[social]]
#   name = "linkedin"
#   weight = 3
#   url = "https://www.linkedin.com/in/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
